name: Spring Boot CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Make mvnw executable
      - name: Give permission to mvnw
        run: chmod +x mvnw

      # 4. Clean & Compile
      - name: Build project
        run: ./mvnw clean compile

      # 5. Run Tests (IMPORTANT ✅)
      - name: Run Tests
        run: ./mvnw test

      # 6. Package JAR
      - name: Package application
        run: ./mvnw package

      # 7. Upload artifact
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-app
          path: target/*.jar